name: "Tests"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        go_version:
          - '1.25'
          - '1.26'

    name: 'Tests - go v${{ matrix.go_version }}'

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version: '${{ matrix.go_version }}'
          cache: true

      - name: 'vet'
        # language=bash
        run: |
          go vet ./...

      - name: 'test'
        # language=bash
        run: |
          go test ./...