name: "Tests"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        go_version:
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'

    name: 'Tests - go v${{ matrix.go_version }}'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go_version }}'
          cache: true

      - name: 'vet'
        run: |
          go vet ./...

      - name: 'test'
        run: |
          go test ./...